import { IProduct } from '~/fake-server/interfaces/newProduct';

export const diameters = [
  {
    diameter: '1/4',
    metric: '1/4-20',
  },
  {
    diameter: '5/16',
    metric: '5/16-18',
  },
  {
    diameter: '3/8',
    metric: '3/8-16',
  },
  {
    diameter: '1/8',
    metric: '1/2-13',
  },
  {
    diameter: '1/2',
  },
  {
    diameter: '3/4-10',
  },
  {
    diameter: '1/4-10',
  },
  {
    diameter: '5/16-9',
  },
  {
    diameter: '3/8-7',
  },
  {
    diameter: '1/2-6',
  },
  {
    diameter: '8-32',
  },
  {
    diameter: '10-24',
  },
  {
    diameter: '6-32',
  },
  {
    diameter: '7/8-9',
  },
  {
    diameter: '1-8',
  },
];

export const sheet13 = [
  {
    Category: 'Conical ',
    description: '6-8 -- Conical Plastic Anchor',
    diameter: '6-8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '8-10 -- Conical Plastic Anchor',
    diameter: '8-10',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '10-12 -- Conical Plastic Anchor',
    diameter: '10-12',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '14-16 -- Conical Plastic Anchor',
    diameter: '14-16',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'E-Z ',
    description: 'E-Z Anchor -- Metal',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Metal',
    Finish: 'n/a',
  },
  {
    Category: 'E-Z ',
    description: 'E-Z Anchor -- Nylon',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Hammer Drive ',
    description: '3/16 x 7/8 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '3/16',
    length: '7/8',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 3/4 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '1/4',
    length: '3/4',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/2 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/4 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/4',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/2 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 2 -- Hammer Drive -- Anchor -- Zinc Plated',
    diameter: '1/4',
    length: '2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-XS -- Hollow Wall -- Anchor',
    diameter: '1/8-XS',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-S -- Hollow Wall -- Anchor',
    diameter: '1/8-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-L -- Hollow Wall -- Anchor',
    diameter: '1/8-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-XL -- Hollow Wall -- Anchor',
    diameter: '1/8-XL',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-S -- Hollow Wall -- Anchor',
    diameter: '3/16-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-L -- Hollow Wall -- Anchor',
    diameter: '3/16-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-XL -- Hollow Wall -- Anchor',
    diameter: '3/16-XL',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-S -- Hollow Wall -- Anchor',
    diameter: '1/4-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-L -- Hollow Wall -- Anchor',
    diameter: '1/4-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-XL -- Hollow Wall -- Anchor',
    diameter: '1/4-XL',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '10 x 1 -- Hex Washer Head SMS -- 10-12 -- Conical Anchor -- Kit',
    diameter: '10',
    length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '10 x 1 -- Hex Washer Head SMS -- 10-12 -- Conical Anchor -- Kit (Without Driver Bit)',
    diameter: '10',
    length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '10 x 1 -- Combo Pan SMS -- 10-12 -- Conical Anchor -- Kit',
    diameter: '10',
    length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '6 x 3/4 -- Slotted Pan SMS -- 6-8 -- Conical Anchor -- Kit',
    diameter: '6',
    length: '3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '8 x 1 -- Slotted Pan SMS -- 8-10 -- Conical Anchor -- Kit',
    diameter: '8',
    length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '10 x 1 -- Slotted Pan SMS -- 10-12 -- Conical Anchor -- Kit',
    diameter: '10',
    length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '12 x 1-1/4 -- Slotted Pan SMS -- 14-16 -- Conical Anchor -- Kit',
    diameter: '12',
    length: '1 1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '14 x 1-1/2 -- Slotted Pan SMS -- 14-16 -- Conical Anchor -- Kit',
    diameter: '14',
    length: '1 1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Nail ',
    description: '3/16 x 1 -- Flat Head -- Nylon Nail -- Anchor',
    diameter: '3/16',
    length: '1',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1 -- Flat Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '1',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1-1/2 -- Flat Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '1-1/2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 2 -- Flat Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1 -- Mushroom Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '1',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1-1/2 -- Mushroom Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '1-1/2',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 2 -- Mushroom Head -- Nylon Nail -- Anchor',
    diameter: '1/4',
    length: '2',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Drop-In',
    description: '1/4-20 -- Drop-In Anchor -- Steel -- Zinc Plated',
    diameter: '1/4-20',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '3/8-16 -- Drop-In Anchor -- Steel -- Zinc Plated',
    diameter: '3/8-16',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '1/2-13 -- Drop-In Anchor -- Steel -- Zinc Plated',
    diameter: '1/2-13',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '5/8-11 -- Drop-In Anchor -- Steel -- Zinc Plated',
    diameter: '5/8-11',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '3/4-10 -- Drop-In Anchor -- Steel -- Zinc Plated',
    diameter: '3/4-10',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Machine Screw',
    description: '6-32 -- Machine Screw Anchor',
    diameter: '6-32',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '8-32 -- Machine Screw Anchor',
    diameter: '8-32',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '10-24 -- Machine Screw Anchor',
    diameter: '10-24',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '1/4-20 -- Machine Screw Anchor',
    diameter: '1/4-20',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '5/16-18 -- Machine Screw Anchor',
    diameter: '5/16-18',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '3/8-16 -- Machine Screw Anchor',
    diameter: '3/8-16',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '1/2-13 -- Machine Screw Anchor',
    diameter: '1/2-13',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '5/8-11 -- Machine Screw Anchor',
    diameter: '5/8-11',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '3/4-10 -- Machine Screw Anchor',
    diameter: '3/4-10',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#6 -- Machine Screw Anchor -- Setting Tool',
    diameter: '#6',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#8 -- Machine Screw Anchor -- Setting Tool',
    diameter: '#8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#10 -- Machine Screw Anchor -- Setting Tool',
    diameter: '#10',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.25 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.25',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.3125 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.3125',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.375 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.375',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.5 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.5',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.625 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.625',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.75 -- Machine Screw Anchor -- Setting Tool',
    diameter: '0.75',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '1/4 -- Drop-In Anchor -- Setting Tools',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '3/8 -- Drop-In Anchor -- Setting Tools',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '1/2 -- Drop-In Anchor -- Setting Tools',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '5/8 -- Drop-In Anchor -- Setting Tools',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '3/4 -- Drop-In Anchor -- Setting Tools',
    diameter: 'n/a',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4-S -- Lag Screw --  -- Shield',
    diameter: '1/4-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16-S -- Lag Screw -- Shield',
    diameter: '5/16-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8-S -- Lag Screw -- Shield',
    diameter: '3/8-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2-S -- Lag Screw -- Shield',
    diameter: '1/2-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8-S -- Lag Screw -- Shield',
    diameter: '5/8-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4-S -- Lag Screw -- Shield',
    diameter: '3/4-S',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4-L -- Lag Screw -- Shield',
    diameter: '1/4-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16-L -- Lag Screw -- Shield',
    diameter: '5/16-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8-L -- Lag Screw -- Shield',
    diameter: '3/8-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2-L -- Lag Screw -- Shield',
    diameter: '1/2-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8-L -- Lag Screw -- Shield',
    diameter: '5/8-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4-L -- Lag Screw -- Shield',
    diameter: '3/4-L',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4 -- Single Expansion -- Shield',
    diameter: '1/4',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16 -- Single Expansion -- Shield',
    diameter: '5/16',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8 -- Single Expansion -- Shield',
    diameter: '3/8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2 -- Single Expansion -- Shield',
    diameter: '1/2',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8 -- Single Expansion -- Shield',
    diameter: '5/8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4 -- Single Expansion -- Shield',
    diameter: '3/4',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4 -- Double Expansion -- Shield',
    diameter: '1/4',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16 -- Double Expansion -- Shield',
    diameter: '5/16',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8 -- Double Expansion -- Shield',
    diameter: '3/8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2 -- Double Expansion -- Shield',
    diameter: '1/2',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8 -- Double Expansion -- Shield',
    diameter: '5/8',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4 -- Double Expansion -- Shield',
    diameter: '3/4',
    length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 X 1-3/8 -- Sleeve Anchor -- Acorn Nut -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-3/8',
    Head_type: 'Acorn Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 X 2-1/4 -- Sleeve Anchor -- Acorn Nut -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2-1/4',
    Head_type: 'Acorn Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/16 X 1-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '1-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/16 X 2-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '2-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 X 1-7/8 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '1-7/8',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '3/8 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '3/8 X 4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/2 X 2-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '2-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 6 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '6',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/8 X 2-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '2-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '5/8 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/8 X 4-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '4-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '5/8 X 6 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '6',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 2-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '2-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 4-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '4-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 6-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '6-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 2 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 3 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '3',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 4 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '4',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 3 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 4 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '4',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 5 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '5',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 6 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '6',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 1-1/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 2 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 2-1/2 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '2-1/2',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 3-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 4-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '4-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 5-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '5-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 6 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '6',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 X 1-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 2-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 3-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '3-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 5 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 2-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 3-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 4-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 5-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 3-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '3-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 4-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '4-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 5 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 8-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '4-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4-5-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 8-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 10 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '3/4',
    length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '7/8',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 8 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '7/8',
    length: '8',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 10 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '7/8',
    length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 9 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1',
    length: '9',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 12 -- Wedge Anchor -- Steel -- Zinc Plated',
    diameter: '1',
    length: '12',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 X 1-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/4',
    length: '1-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 2-1/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/4',
    length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 3-1/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/4',
    length: '3-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-1/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/8',
    length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/8',
    length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/8',
    length: '3',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/8',
    length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 5 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/8',
    length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 2-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/2',
    length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 3-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/2',
    length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 4-1/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/2',
    length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 5-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/2',
    length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 7 -- Wedge Anchor -- Stainless Steel',
    diameter: '1/2',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 3-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '3-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 4-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '4-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 5 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 6 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 7 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 8-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '5/8',
    length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-1/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-3/4 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '4-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4-5-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 7 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 8-1/2 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 10 -- Wedge Anchor -- Stainless Steel',
    diameter: '3/4',
    length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 6 -- Wedge Anchor -- Stainless Steel',
    diameter: '7/8',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 8 -- Wedge Anchor -- Stainless Steel',
    diameter: '7/8',
    length: '8',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 10 -- Wedge Anchor -- Stainless Steel',
    diameter: '7/8',
    length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 6 -- Wedge Anchor -- Stainless Steel',
    diameter: '1',
    length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 9 -- Wedge Anchor -- Stainless Steel',
    diameter: '1',
    length: '9',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 12 -- Wedge Anchor -- Stainless Steel',
    diameter: '1',
    length: '12',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
];

export const Sheet12 = [
  {
    Head_type: 'Acorn Nut',
    Drive: 'Combo',
    Grade: '2',
    Material: 'Metal',
    Finish: 'Black Oxide',
  },
  {
    Head_type: 'Bugle',
    Drive: 'Hex',
    Grade: '5',
    Material: 'Nylon',
    Finish: 'Black Phosphate',
  },
  {
    Head_type: 'Flat',
    Drive: 'Phillips',
    Grade: '8',
    Material: 'Plastic',
    Finish: 'Black Phosphate & Oil',
  },
  {
    Head_type: 'Flat Head',
    Drive: 'Slotted',
    Grade: '18-8',
    Material: 'Stainless Steel',
    Finish: 'Blue',
  },
  {
    Head_type: 'Full Thread',
    Drive: 'Slotted Hex',
    Grade: '18-8SS',
    Material: 'Steel',
    Finish: 'Brown',
  },
  {
    Head_type: 'Hammer Drive',
    Grade: '303SS',
    Finish: 'Dacrotized',
  },
  {
    Head_type: 'Hex',
    Grade: '5',
    Finish: 'Hot Dip Galvanized',
  },
  {
    Head_type: 'Hex Cap',
    Grade: '8',
    Finish: 'Ivory',
  },
  {
    Head_type: 'Hex Nut',
    Grade: 'Alloy',
    Finish: 'Nickel',
  },
  {
    Head_type: 'Hex Washer',
    Grade: 'C',
    Finish: 'Nylon',
  },
  {
    Head_type: 'Indented Hex Flange',
    Grade: 'G',
    Finish: 'Plain',
  },
  {
    Head_type: 'Mushroom',
    Grade: 'Hardened',
    Finish: 'White',
  },
  {
    Head_type: 'Mushroom Head',
    Finish: 'Zinc',
  },
  {
    Head_type: 'Oval',
    Finish: 'Zinc & Dichromate',
  },
  {
    Head_type: 'Pan',
    Finish: 'Zinc Yellow',
  },
  {
    Head_type: 'Round',
  },
  {
    Head_type: 'Round Head',
  },
  {
    Head_type: 'Slotted',
  },
];

export const Attributes = [
  {
    diameter: '#4',
    length: 'xs',
    threadSize: 'Inch',
    metric: 'Fine',
    'Thread Type (metric)': 'Coarse',
    screwSize: '6-8',
  },
  {
    diameter: '#6',
    length: 's',
    threadSize: 'Coarse',
    metric: 'Partial',
    'Thread Type (metric)': 'Full',
    screwSize: '8-10',
  },
  {
    diameter: '#8',
    length: 'l',
    threadSize: '#2-56',
    metric: 'DIN 960',
    'Thread Type (metric)': 'DIN 933',
    screwSize: '10-12',
  },
  {
    diameter: '#10',
    length: 'xl',
    threadSize: '#3-48',
    metric: 'M4-0.7',
    screwSize: '14-16',
  },
  {
    diameter: '1/8',
    length: 'short',
    threadSize: '#4-40',
    metric: 'M5-0.8',
  },
  {
    diameter: '3/16',
    length: 'long',
    threadSize: '#6-32',
    metric: 'M6-1.00',
  },
  {
    diameter: '1/4',
    threadSize: '#8-32',
    metric: 'M7-1.00',
  },
  {
    diameter: '5/16',
    threadSize: '#10-24',
    metric: 'M8-1.00',
  },
  {
    diameter: '3/8',
    threadSize: '1/4"-20',
    metric: 'M10-1.00',
  },
  {
    diameter: '7/16',
    threadSize: '5/16"-18',
    metric: 'M10-1.25',
  },
  {
    diameter: '1/2',
    threadSize: '3/8"-16',
    metric: 'M12-1.25',
  },
  {
    diameter: '9/16',
    threadSize: '7/16"-14',
    metric: 'M12-1.50',
  },
  {
    diameter: '5/8',
    threadSize: '1/2"-13',
    metric: 'M14-1.50',
  },
  {
    diameter: '3/4',
    threadSize: '9/16"-12',
    metric: 'M16-1.50',
  },
  {
    diameter: '7/8',
    threadSize: '5/8"-11',
    metric: 'M18-1.50',
  },
  {
    diameter: '1',
    threadSize: '3/4"-10',
    metric: 'M20-1.50',
  },
  {
    diameter: '1 1/8',
    threadSize: '7/8"-9',
    metric: 'M22-1.50',
  },
  {
    diameter: '1 1/4',
    threadSize: '1"-8',
    metric: 'M24-2.00',
  },
  {
    diameter: '1 3/8',
    threadSize: '1-1/8"-7',
    metric: 'M27-3.00',
  },
  {
    diameter: '1 1/2',
    threadSize: '1-1/4"-7',
    metric: 'M30-3.50',
  },
  {
    diameter: '1 3/4',
    threadSize: '1-3/8"-6',
    metric: 'M33-3.50',
  },
  {
    diameter: '2',
    threadSize: '1-1/2"-6',
    metric: 'M36-4.00',
  },
  {
    diameter: '2 1/4',
    threadSize: '1-3/4"-5',
    metric: 'M39-4.00',
  },
  {
    diameter: '2 1/2',
    threadSize: '2"-4-1/2',
    metric: 'M42-4.50',
  },
  {
    diameter: '2 3/4',
    threadSize: '2-1/2"-4-12',
    metric: 'M45-4.50',
  },
  {
    diameter: '3',
    threadSize: '2-3/4"-4',
    metric: 'M48-5.00',
  },
  {
    threadSize: '3"-4',
    metric: '3"-12',
  },
];

export const attributes_2 = [
  {
    diameter: '#2',
    length: 'xs',
    'Threads (Coarse)': '#2-56',
    'Threads (Fine)': '#10-32',
    'Thread Type (metric)': 'Coarse',
    threadSize: 'Inch',
    metric: 'Fine',
    screwSize: '6-8',
  },
  {
    diameter: '#3',
    length: 's',
    'Threads (Coarse)': '#3-48',
    'Threads (Fine)': '1/4"-28',
    'Thread Type (metric)': 'Full',
    threadSize: 'Coarse',
    metric: 'Partial',
    screwSize: '8-10',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    diameter: '#4',
    length: 'l',
    'Threads (Coarse)': '#4-40',
    'Threads (Fine)': '5/16"-24',
    threadSize: '#2-56',
    metric: 'DIN 960',
    'Thread Type (metric)': 'DIN 933',
    screwSize: '10-12',
    Material: 'Stainless Steel',
    Finish: 'Zinc & Dichromate',
  },
  {
    diameter: '#6',
    length: 'xl',
    'Threads (Coarse)': '#6-32',
    'Threads (Fine)': '3/8"-24',
    threadSize: '#3-48',
    metric: 'FILTERS',
    screwSize: '14-16',
    Finish: 'n/a',
  },
  {
    diameter: '#8',
    length: 'short',
    'Threads (Coarse)': '#8-32',
    'Threads (Fine)': '7/16"-20',
    threadSize: '#4-40',
    metric: 'threadSize',
  },
  {
    diameter: '#10',
    length: 'long',
    'Threads (Coarse)': '#10-24',
    'Threads (Fine)': '1/2"-20',
    threadSize: '#6-32',
    metric: 'Metric',
  },
  {
    diameter: '1/8',
    'Threads (Coarse)': '1/4"-20',
    'Threads (Fine)': '9/16"-18',
    threadSize: '#8-32',
    metric: 'Inch',
  },
  {
    diameter: '3/16',
    'Threads (Coarse)': '5/16"-18',
    'Threads (Fine)': '5/8"-18',
    threadSize: '#10-24',
    metric: 'M8-1.00',
  },
  {
    diameter: '1/4',
    'Threads (Coarse)': '3/8"-16',
    'Threads (Fine)': '3/4"-16',
    threadSize: '1/4"-20',
    metric: 'Coarse',
  },
  {
    diameter: '5/16',
    'Threads (Coarse)': '7/16"-14',
    'Threads (Fine)': '7/8"-14',
    threadSize: '5/16"-18',
    metric: 'Fine',
  },
  {
    diameter: '3/8',
    'Threads (Coarse)': '1/2"-13',
    'Threads (Fine)': '1"-14',
    threadSize: '3/8"-16',
    metric: 'M12-1.25',
  },
  {
    diameter: '7/16',
    'Threads (Coarse)': '9/16"-12',
    'Threads (Fine)': '1-1/8"-12',
    threadSize: '7/16"-14',
    metric: 'Full',
  },
  {
    diameter: '1/2',
    'Threads (Coarse)': '5/8"-11',
    'Threads (Fine)': '1-1/4"-12',
    threadSize: '1/2"-13',
    metric: 'Partial',
  },
  {
    diameter: '9/16',
    'Threads (Coarse)': '3/4"-10',
    'Threads (Fine)': '1-3/8"-12',
    threadSize: '9/16"-12',
    metric: 'M16-1.50',
  },
  {
    diameter: '5/8',
    'Threads (Coarse)': '7/8"-9',
    'Threads (Fine)': '1-1/2"-12',
    threadSize: '5/8"-11',
    metric: 'M18-1.50',
  },
  {
    diameter: '3/4',
    'Threads (Coarse)': '1"-8',
    'Threads (Fine)': '1-3/4"-12',
    threadSize: '3/4"-10',
    metric: 'M20-1.50',
  },
  {
    diameter: '7/8',
    'Threads (Coarse)': '1-1/8"-7',
    'Threads (Fine)': '2"-12',
    threadSize: '7/8"-9',
    metric: 'M22-1.50',
  },
  {
    diameter: '1',
    'Threads (Coarse)': '1-1/4"-7',
    'Threads (Fine)': '2-1/2"-12',
    threadSize: '1"-8',
    metric: 'M24-2.00',
  },
  {
    diameter: '1 1/8',
    'Threads (Coarse)': '1-3/8"-6',
    'Threads (Fine)': '2-3/4"-12',
    threadSize: '1-1/8"-7',
    metric: 'M27-3.00',
  },
  {
    diameter: '1 1/4',
    'Threads (Coarse)': '1-1/2"-6',
    'Threads (Fine)': '3"-12',
    threadSize: '1-1/4"-7',
    metric: 'M30-3.50',
  },
  {
    diameter: '1 3/8',
    'Threads (Coarse)': '1-3/4"-5',
    'Threads (Fine)': 'M8-1.00',
    threadSize: '1-3/8"-6',
    metric: 'M33-3.50',
  },
  {
    diameter: '1 1/2',
    'Threads (Coarse)': '2"-4-1/2',
    'Threads (Fine)': 'M10-1.00',
    threadSize: '1-1/2"-6',
    metric: 'M36-4.00',
  },
  {
    diameter: '1 3/4',
    'Threads (Coarse)': '2-1/2"-4-12',
    'Threads (Fine)': 'M10-1.25',
    threadSize: '1-3/4"-5',
    metric: 'M39-4.00',
  },
  {
    diameter: '2',
    'Threads (Coarse)': '2-3/4"-4',
    'Threads (Fine)': 'M12-1.25',
    threadSize: '2"-4-1/2',
    metric: 'M42-4.50',
  },
  {
    diameter: '2 1/4',
    'Threads (Coarse)': '3"-4',
    'Threads (Fine)': 'M12-1.50',
    threadSize: '2-1/2"-4-12',
    metric: 'M45-4.50',
  },
  {
    diameter: '2 1/2',
    'Threads (Coarse)': 'M3-0.5',
    'Threads (Fine)': 'M14-1.50',
    threadSize: '2-3/4"-4',
    metric: 'M48-5.00',
  },
  {
    diameter: '2 3/4',
    'Threads (Coarse)': 'M4-0.7',
    'Threads (Fine)': 'M16-1.50',
    threadSize: '3"-4',
    metric: '3"-12',
  },
  {
    diameter: '3',
    'Threads (Coarse)': 'M5-0.8',
    'Threads (Fine)': 'M18-1.50',
  },
  {
    'Threads (Coarse)': 'M6-1.00',
    'Threads (Fine)': 'M20-1.50',
  },
  {
    'Threads (Coarse)': 'M7-1.00',
    'Threads (Fine)': 'M22-1.50',
  },
  {
    'Threads (Coarse)': 'M8-1.25',
    'Threads (Fine)': 'M24-2.00',
  },
  {
    'Threads (Coarse)': 'M10-1.50',
  },
  {
    'Threads (Coarse)': 'M12-1.75',
  },
  {
    'Threads (Coarse)': 'M14-2.00',
  },
  {
    'Threads (Coarse)': 'M16-2.00',
  },
  {
    'Threads (Coarse)': 'M18-2.50',
  },
  {
    'Threads (Coarse)': 'M20-2.50',
  },
  {
    'Threads (Coarse)': 'M22-2.50',
  },
  {
    'Threads (Coarse)': 'M24-3.00',
  },
  {
    'Threads (Coarse)': 'M27-3.00',
  },
  {
    'Threads (Coarse)': 'M30-3.50',
  },
  {
    'Threads (Coarse)': 'M33-3.50',
  },
  {
    'Threads (Coarse)': 'M36-4.00',
  },
  {
    'Threads (Coarse)': 'M39-4.00',
  },
  {
    'Threads (Coarse)': 'M42-4.50',
  },
  {
    'Threads (Coarse)': 'M45-4.50',
  },
  {
    'Threads (Coarse)': 'M48-5.00',
  },
];

export const attribute_3: any[] = [
  {
    diameter: '#2',
    length: 'xs',
    threadSize: 'Inch',
    threadCoverage: 'Full',
    screwSize: '6-8',
  },
  {
    diameter: '#3',
    length: 's',
    threadLength: {
      threadlength: '1/8',
      metric: '5',
    },
    threadSize: {
      threadSize: '#2-56',
      metric: 'M10-1.00',
    },
    threadCoverage: 'Partial',
    screwSize: '8-10',
  },
  {
    diameter: '#4',
    length: 'l',
    threadLength: {
      metric: '6',
      threadlength: '3/16',
    },
    threadSize: {
      threadSize: '#3-48',
      metric: 'M10-1.25',
    },
    screwSize: '10-12',
  },
  {
    diameter: '#6',
    length: 'xl',
    threadLength: {
      metric: '8',
      threadlength: '1/4',
    },
    threadSize: {
      threadSize: '#4-40',
      metric: 'M10-1.50',
    },
    screwSize: '14-16',
  },
  {
    diameter: '#8',
    length: 'short',
    threadLength: {
      metric: '10',
      threadlength: '5/16',
    },
    threadSize: {
      threadSize: '#6-32',
      metric: 'M12-1.25',
    },
  },
  {
    diameter: '#10',
    length: 'long',
    threadLength: {
      metric: '12',
      threadlength: '3/8',
    },
    threadSize: {
      threadSize: '#8-32',
      metric: 'M12-1.50',
    },
  },
  {
    diameter: '1/8',

    threadLength: {
      metric: '14',
      threadlength: '7/16',
    },
    threadSize: {
      threadSize: '#10-24',
      metric: 'M12-1.75',
    },
  },
  {
    diameter: '3/16',

    threadLength: {
      metric: '16',
      threadlength: '1/2',
    },
    threadSize: {
      threadSize: '#10-32',
      metric: 'M14-1.50',
    },
  },
  {
    diameter: '1/4',
    threadLength: {
      metric: '18',
      threadlength: '5/8',
    },
    threadSize: {
      threadSize: '1/2"-13',
      metric: 'M14-2.00',
    },
  },
  {
    diameter: '5/16',
    threadLength: {
      metric: '20 ',
      threadlength: '3/4',
    },
    threadSize: {
      threadSize: '1/2"-20',
      metric: 'M16-1.50',
    },
  },
  {
    diameter: '3/8',
    threadLength: {
      metric: '25 ',
      threadlength: '7/8',
    },
    threadSize: {
      threadSize: '1/4"-20',
      metric: 'M16-2.00',
    },
  },
  {
    diameter: '7/16',
    threadLength: {
      metric: '30 ',
      threadlength: '1',
    },
    threadSize: {
      threadSize: '1/4"-28',
      metric: 'M18-1.50',
    },
  },
  {
    diameter: '1/2',
    threadLength: {
      metric: '35 ',
      threadlength: '1 1/8',
    },
    threadSize: {
      threadSize: '3/4"-10',
      metric: 'M18-2.50',
    },
  },
  {
    diameter: '9/16',
    threadLength: {
      metric: '40 ',
      threadlength: '1 1/4',
    },
    threadSize: {
      threadSize: '3/4"-16',
      metric: 'M20-1.50',
    },
  },
  {
    diameter: '5/8',
    threadLength: {
      metric: '45 ',
      threadlength: '1 3/8',
    },
    threadSize: {
      threadSize: '3/8"-16',
      metric: 'M20-2.50',
    },
  },
  {
    diameter: '3/4',
    threadLength: {
      metric: '50 ',
      threadlength: '1 1/2',
    },
    threadSize: {
      threadSize: '3/8"-24',
      metric: 'M22-1.50',
    },
  },
  {
    diameter: '7/8',
    threadLength: {
      metric: '55 ',
      threadlength: '1 3/4',
    },
    threadSize: {
      threadSize: '5/16"-18',
      metric: 'M22-2.50',
    },
  },
  {
    diameter: '1',
    threadLength: {
      metric: '60',
      threadlength: '2',
    },
    threadSize: {
      threadSize: '5/16"-24',
      metric: 'M24-2.00',
    },
  },
  {
    diameter: '1 1/8',
    threadLength: {
      metric: '65',
      threadlength: '2 1/4',
    },
    threadSize: {
      threadSize: '5/8"-11',
      metric: 'M24-3.00',
    },
  },
  {
    diameter: '1 1/4',
    threadLength: {
      metric: '70',
      threadlength: '2 1/2',
    },
    threadSize: {
      threadSize: '5/8"-18',
      metric: 'M27-3.00',
    },
  },
  {
    diameter: '1 3/8',
    threadLength: {
      metric: '75',
      threadlength: '2 3/4',
    },
    threadSize: {
      threadSize: '7/16"-14',
      metric: 'M3-0.5',
    },
  },
  {
    diameter: '1 1/2',
    threadLength: {
      metric: '80',
      threadlength: '3',
    },
    threadSize: {
      threadSize: '7/16"-20',
      metric: 'M30-3.50',
    },
  },
  {
    diameter: '1 3/4',
    threadLength: {
      metric: '90',
      threadlength: '3 1/4',
    },
    threadSize: {
      threadSize: '7/8"-14',
      metric: 'M33-3.50',
    },
  },
  {
    diameter: '2',
    threadLength: {
      metric: '100',
      threadlength: '3 1/2',
    },
    threadSize: {
      threadSize: '7/8"-9',
      metric: 'M36-4.00',
    },
  },
  {
    diameter: '2 1/4',
    threadLength: {
      metric: '110',
      threadlength: '3 3/4',
    },
    threadSize: {
      threadSize: '9/16"-12',
      metric: 'M39-4.00',
    },
  },
  {
    diameter: '2 1/2',
    threadLength: {
      metric: '120',
      threadlength: '4',
    },
    threadSize: {
      threadSize: '9/16"-18',
      metric: 'M4-0.7',
    },
  },
  {
    diameter: '2 3/4',
    threadLength: {
      metric: '130',
      threadlength: '4 1/4',
    },
    threadSize: {
      threadSize: '1-1/2"-12',
      metric: 'M42-4.50',
    },
  },
  {
    diameter: '3',
    threadLength: {
      metric: '140 ',
      threadlength: '4 1/2',
    },
    threadSize: {
      threadSize: '1-1/2"-6',
      metric: 'M45-4.50',
    },
  },
  {
    threadLength: {
      metric: '150',
      threadlength: '4 3/4',
    },
    threadSize: {
      threadSize: '1-1/4"-12',
      metric: 'M48-5.00',
    },
  },
  {
    threadLength: {
      metric: '160 ',
      threadlength: '5',
    },
    threadSize: {
      threadSize: '1-1/4"-7',
      metric: 'M5-0.8',
    },
  },
  {
    threadLength: {
      metric: '170',
      threadlength: '5 1/2',
    },
    threadSize: {
      threadSize: '1-1/8"-12',
      metric: 'M6-1.00',
    },
  },
  {
    threadLength: {
      metric: '180',
      threadlength: '6',
    },
    threadSize: {
      threadSize: '1-1/8"-7',
      metric: 'M7-1.00',
    },
  },
  {
    threadLength: {
      metric: '200',
      threadlength: '6 1/2',
    },
    threadSize: {
      threadSize: '1-3/4"-12',
      metric: 'M8-1.00',
    },
  },
  {
    threadLength: {
      threadlength: '7',
    },
    threadSize: {
      threadSize: '1-3/4"-5',
      metric: 'M8-1.25',
    },
  },
  {
    threadSize: '1-3/8"-12',
    threadLength: {
      threadlength: '7 1/2',
    },
  },
  {
    threadSize: '1-3/8"-6',
    threadLength: {
      threadlength: '8',
    },
  },
  {
    threadSize: '1"-14',
    threadLength: {
      threadlength: '8 1/2',
    },
  },
  {
    threadSize: '1"-8',
    threadLength: {
      threadlength: '9',
    },
  },
  {
    threadSize: '2-1/2"-12',
    threadLength: {
      threadlength: '9 1/2',
    },
  },
  {
    threadSize: '2-1/2"-4-12',
    threadLength: {
      threadlength: '10',
    },
  },
  {
    threadSize: '2-3/4"-12',
    threadLength: {
      threadlength: '11',
    },
  },
  {
    threadSize: '2-3/4"-4',
    threadLength: {
      threadlength: '12',
    },
  },
  {
    threadSize: '2"-12',
    threadLength: {
      threadlength: '13',
    },
  },
  {
    threadSize: '2"-4-1/2',
    threadLength: {
      threadlength: '14',
    },
  },
  {
    threadSize: '3"-12',
    threadLength: {
      threadlength: '15',
    },
  },
  {
    threadSize: '3"-4',
    threadLength: {
      threadlength: '16',
    },
  },
];

export const Sheet_16 = [
  {
    threadSize: 'Inch',
    metric: '$???',
    threadlength: 'Inch',
  },
  {
    threadSize: '#2-56',
    metric: '$???',
    threadlength: '1/8',
  },
  {
    threadSize: '#3-48',
    metric: '$???',
    threadlength: '3/16',
  },
  {
    threadSize: '#4-40',
    metric: '$???',
    threadlength: '1/4',
  },
  {
    threadSize: '#6-32',
    metric: '10',
    threadlength: '5/16',
  },
  {
    threadSize: '#8-32',
    metric: '12',
    threadlength: '3/8',
  },
  {
    threadSize: '#10-24',
    metric: '14',
    threadlength: '7/16',
  },
  {
    threadSize: '#10-32',
    metric: '16',
    threadlength: '1/2',
  },
  {
    threadSize: '1/2"-13',
    metric: '18',
    threadlength: '5/8',
  },
  {
    threadSize: '1/2"-20',
    metric: '20 ',
    threadlength: '3/4',
  },
  {
    threadSize: '1/4"-20',
    metric: '25 ',
    threadlength: '7/8',
  },
];
