/* eslint-disable import/prefer-default-export */

// application
import { brands } from '~/fake-server/database/brands';
import { IBrand } from '~/interfaces/brand';
import { IProduct, IProductAttribute } from '~/interfaces/product';
import { IShopCategory } from '~/interfaces/category';
import { makeIdGenerator, nameToSlug } from '~/fake-server/utils';
import { prepareCategory } from '~/fake-server/endpoints/categories';
import {
  IProductAttributesDef,
  IProductDef,
} from '~/fake-server/interfaces/product-def';
import { shopCategoriesList } from '~/fake-server/database/categories';

const getNextId = makeIdGenerator();

function resolveProductAttributesDef(
  attributesDef: IProductAttributesDef
): IProductAttribute[] {
  const attributes: IProductAttribute[] = [];
  const keys = Object.keys(attributesDef);

  for (let i = 0; i < keys.length; i += 1) {
    const attributeName = keys[i];
    const attribute: IProductAttribute = {
      name: attributeName,
      slug: nameToSlug(attributeName),
      featured: false,
      values: [],
    };

    const valuesDef = attributesDef[attributeName];
    let valueNames: string[] = [];

    if (typeof valuesDef === 'string') {
      valueNames = [valuesDef];
    } else {
      if (valuesDef[0] === true) {
        attribute.featured = true;
        valuesDef.splice(0, 1);
      }

      valueNames = valuesDef as string[];
    }

    valueNames.forEach((valueName) => {
      attribute.values.push({
        name: valueName,
        slug: nameToSlug(valueName),
      });
    });

    if (attribute.values.length > 0) {
      attributes.push(attribute);
    }
  }

  return attributes;
}

function makeProducts(defs: IProductDef[]): IProduct[] {
  return defs.map((def) => {
    let badges: string[] = [];

    if (def.badges) {
      if (typeof def.badges === 'string') {
        badges = [def.badges];
      } else {
        badges = def.badges.slice(0);
      }
    }

    let brand: IBrand = {
      slug: 'brandix',
      name: 'Brandix',
      image: '',
      country: 'JP',
    };

    if (def.brand) {
      brand = brands.find((x) => x.slug === def.brand) || brand;
    }

    const categorySlugs: string[] = def.categories || ['tools-garage'];
    const categories = categorySlugs
      .map((categorySlug) =>
        shopCategoriesList.find((x) => x.slug === categorySlug)
      )
      .map((x) => (x ? prepareCategory(x) : null))
      .filter((x) => x !== null) as IShopCategory[];

    const attributesDef: IProductAttributesDef = {
      Speed: [true, '750 RPM'],
      'Power Source': [true, 'Cordless-Electric'],
      'Battery Cell Type': [true, 'Lithium'],
      Voltage: [true, '20 Volts'],
      'Battery Capacity': [true, '2 Ah'],
      Material: [
        'Aluminium',
        'Plastic',
        'Metal',
        'Nylon',
        'Steel',
        'Stainless Steel',
      ],
      'Engine Type': 'Brushless',
      Length: '99 mm',
      Width: '207 mm',
      Height: '208 mm',
    };

    return {
      id: getNextId(),
      name: def.name,
      excerpt: `
                Many philosophical debates that began in ancient times are still debated today. In one general sense,
                philosophy is associated with wisdom, intellectual culture and a search for knowledge.
            `,
      description: `
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas fermentum, diam non iaculis finibus,
                    ipsum arcu sollicitudin dolor, ut cursus sapien sem sed purus. Donec vitae fringilla tortor, sed
                    fermentum nunc. Suspendisse sodales turpis dolor, at rutrum dolor tristique id. Quisque pellentesque
                    ullamcorper felis, eget gravida mi elementum a. Maecenas consectetur volutpat ante, sit amet molestie
                    urna luctus in. Nulla eget dolor semper urna malesuada dictum. Duis eleifend pellentesque dui et
                    finibus. Pellentesque dapibus dignissim augue. Etiam odio est, sodales ac aliquam id, iaculis eget
                    lacus. Aenean porta, ante vitae suscipit pulvinar, purus dui interdum tellus, sed dapibus mi mauris
                    vitae tellus.
                </p>
                <h4>Etiam lacus lacus mollis in mattis</h4>
                <p>
                    Praesent mattis eget augue ac elementum. Maecenas vel ante ut enim mollis accumsan. Vestibulum vel
                    eros at mi suscipit feugiat. Sed tortor purus, vulputate et eros a, rhoncus laoreet orci. Proin sapien
                    neque, commodo at porta in, vehicula eu elit. Vestibulum ante ipsum primis in faucibus orci luctus et
                    ultrices posuere cubilia Curae; Curabitur porta vulputate augue, at sollicitudin nisl molestie eget.
                </p>
                <p>
                    Nunc sollicitudin, nunc id accumsan semper, libero nunc aliquet nulla, nec pretium ipsum risus ac
                    neque. Morbi eu facilisis purus. Quisque mi tortor, cursus in nulla ut, laoreet commodo quam.
                    Pellentesque et ornare sapien. In ac est tempus urna tincidunt finibus. Integer erat ipsum, tristique
                    ac lobortis sit amet, dapibus sit amet purus. Nam sed lorem nisi. Vestibulum ultrices tincidunt turpis,
                    sit amet fringilla odio scelerisque non.
                </p>
            `,
      slug: def.slug,
      sku: def.sku,
      partNumber: 'BDX-750Z370-S',
      stock: 'in-stock',
      price: def.price,
      compareAtPrice: def.compareAtPrice || null,
      images: def.images.slice(0),
      badges,
      rating: def.rating,
      reviews: def.reviews,
      availability: def.availability,
      compatibility: def.compatibility || 'all',
      brand,
      type: {
        slug: 'default',
        name: 'Default',
        attributeGroups: [
          {
            name: 'General',
            slug: 'general',
            attributes: [
              'speed',
              'power-source',
              'battery-cell-type',
              'voltage',
              'battery-capacity',
              'material',
              'engine-type',
            ],
          },
          {
            name: 'Dimensions',
            slug: 'dimensions',
            attributes: ['length', 'width', 'height'],
          },
        ],
      },
      attributes: resolveProductAttributesDef({
        ...attributesDef,
        ...def.attributes,
      }),
      options: [
        {
          type: 'default',
          slug: 'material',
          name: 'Material',
          values: [
            { slug: 'steel', name: 'Steel' },
            { slug: 'aluminium', name: 'Aluminium' },
            { slug: 'thorium', name: 'Thorium' },
          ],
        },
        {
          type: 'color',
          slug: 'color',
          name: 'Color',
          values: [
            { slug: 'white', name: 'White', color: '#fff' },
            { slug: 'yellow', name: 'Yellow', color: '#ffd333' },
            { slug: 'red', name: 'Red', color: '#ff4040' },
            { slug: 'blue', name: 'Blue', color: '#4080ff' },
          ],
        },
      ],
      tags: [
        'Brake Kit',
        'Brandix',
        'Filter',
        'Bumper',
        'Transmission',
        'Hood',
      ],
      categories,
      customFields: {},
    };
  });
}

const productsDef: IProductDef[] = [
  {
    name: 'test 1',
    slug: 'test',
    sku: '6335000',
    price: 1.65,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '6336000',
    price: 1.8,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '6337000',
    price: 1.98,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '6338000',
    price: 5.63,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '6333000E',
    price: 85.0,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '6333000Z',
    price: 80.0,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5860028',
    price: 26.68,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5866024',
    price: 34.07,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5866032',
    price: 39.95,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5866040',
    price: 46.94,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5866048',
    price: 53.74,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5866064',
    price: 62.65,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '6450001',
    price: 41.88,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '6450003',
    price: 49.27,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '6450004',
    price: 55.9,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '6450005',
    price: 80.14,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '6450008',
    price: 77.32,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '6450009',
    price: 99.11,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '6450010',
    price: 158.64,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '6450010',
    price: 158.64,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '6450011',
    price: 99.86,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '6450012',
    price: 111.05,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '6450013',
    price: 206.57,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '6431000',
    price: 25.55,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '6335000',
    price: 1.65,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '6336000',
    price: 1.8,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '6337000',
    price: 1.98,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '6338000',
    price: 5.63,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '6333000E',
    price: 85.0,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '6333000Z',
    price: 80.0,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5860028',
    price: 26.68,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5866024',
    price: 34.07,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5866032',
    price: 39.95,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5866040',
    price: 46.94,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5866048',
    price: 53.74,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5866064',
    price: 62.65,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '6450001',
    price: 41.88,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '6450003',
    price: 49.27,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '6450004',
    price: 55.9,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '6450005',
    price: 80.14,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '6450008',
    price: 77.32,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '6450009',
    price: 99.11,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '6450010',
    price: 158.64,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '6450010',
    price: 158.64,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '6450011',
    price: 99.86,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '6450012',
    price: 111.05,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '6450013',
    price: 206.57,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '6431000',
    price: 25.55,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  }, /////
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '6431000WD',
    price: 15.95,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '6433000',
    price: 14.55,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '6435000',
    price: 10.95,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '6436000',
    price: 12.6,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '6437000',
    price: 13.25,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '6438000',
    price: 21.5,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '6439000',
    price: 33.0,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5870032',
    price: 16.26,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5876032',
    price: 19.25,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5876048',
    price: 24.97,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5876064',
    price: 31.41,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5896032',
    price: 19.25,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '5896048',
    price: 24.97,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '5896064',
    price: 31.41,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '7316000-ZN',
    price: 99.08,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '7318000-ZN',
    price: 134.57,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '7320000-ZN',
    price: 114.04,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '7322000-ZN',
    price: 119.36,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '7323000-ZN',
    price: 207.47,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '7206000',
    price: 63.07,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '7208000',
    price: 68.79,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '7210000',
    price: 68.43,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '7216000',
    price: 65.78,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '7217000',
    price: 120.96,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '7218000',
    price: 101.76,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '7220000',
    price: 108.58,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '7222000',
    price: 106.25,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '7223000',
    price: 213.44,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '7606000',
    price: 5.58,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '7608000',
    price: 5.58,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '7610000',
    price: 6.3,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '7616000',
    price: 5.65,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '7617000',
    price: 7.88,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '7618000',
    price: 8.64,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '7620000',
    price: 9.78,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '7622000',
    price: 23.26,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '7623000',
    price: 24.61,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '7716000',
    price: 9.96,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '7718000',
    price: 11.63,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '7720000',
    price: 15.18,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '7722000',
    price: 21.27,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '7723000',
    price: 28.77,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '7460000',
    price: 26.37,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '7461000',
    price: 29.28,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '7462000',
    price: 58.02,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '7463000',
    price: 92.0,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '7464000',
    price: 67.42,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '7465000',
    price: 79.29,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '7466000',
    price: 39.58,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '7467000',
    price: 42.86,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '7468000',
    price: 82.82,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '7469000',
    price: 133.9,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '7470000',
    price: 128.61,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '7471000',
    price: 168.84,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '7516000',
    price: 122.68,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '7517000',
    price: 94.59,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '7518000',
    price: 119.84,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '7520000',
    price: 154.65,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '7522000',
    price: 162.8,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '7523000',
    price: 257.2,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '7516002',
    price: 117.65,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '7517002',
    price: 97.27,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '7518002',
    price: 145.11,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '7520002',
    price: 180.11,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '7522002',
    price: 138.77,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '7523002',
    price: 108.35,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '5856044-ZN',
    price: 70.93,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '5856072-ZN',
    price: 76.51,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '5717048-ZN',
    price: 76.5,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '5717080-ZN',
    price: 99.57,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '5718060-ZN',
    price: 64.57,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '5718096-ZN',
    price: 73.68,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '5718128-ZN',
    price: 89.0,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '5720072-ZN',
    price: 59.75,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '5720096-ZN',
    price: 67.22,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '5720128-ZN',
    price: 81.95,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '5720192-ZN',
    price: 99.61,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '5722072-ZN',
    price: 88.05,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5722096-ZN',
    price: 107.47,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5722136-ZN',
    price: 62.57,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5722192-ZN',
    price: 65.61,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5723080-ZN',
    price: 66.07,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5723136-ZN',
    price: 76.0,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5723200-ZN',
    price: 62.14,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '5816064-ZN',
    price: 113.0,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '5816096-ZN',
    price: 120.68,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '5816128-ZN',
    price: 144.11,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '5818096-ZN',
    price: 86.86,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '5818128-ZN',
    price: 111.32,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '5818160-ZN',
    price: 134.93,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '5818192-ZN',
    price: 154.75,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '5826040-ZN',
    price: 99.79,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '5826064-ZN',
    price: 122.71,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '5926088-ZN',
    price: 132.0,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '5828080-ZN',
    price: 104.86,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '5828120-ZN',
    price: 117.54,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '5828152-ZN',
    price: 153.15,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '5828184-ZN',
    price: 163.86,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '5828192-ZN',
    price: 206.54,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '5616056-ZN',
    price: 87.86,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '5616072-ZN',
    price: 98.64,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '5616104-ZN',
    price: 113.86,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '5618072-ZN',
    price: 139.93,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '5618088-ZN',
    price: 158.71,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '5618096-ZN',
    price: 162.29,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '5618120-ZN',
    price: 188.71,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '5618160-ZN',
    price: 117.82,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '5620088-ZN',
    price: 106.04,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5620120-ZN',
    price: 145.43,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5620136-ZN',
    price: 89.3,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5620176-ZN',
    price: 96.75,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5620224-ZN',
    price: 118.6,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5622112-ZN',
    price: 117.64,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5622144-ZN',
    price: 127.14,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '5622160-ZN',
    price: 146.51,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '5622192-ZN',
    price: 161.77,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '5622224-ZN',
    price: 182.93,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '5622272-ZN',
    price: 212.7,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '5623136-ZN',
    price: 129.14,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '5623152-ZN',
    price: 152.64,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '5623176-ZN',
    price: 164.03,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '5623224-ZN',
    price: 107.34,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '5623272-ZN',
    price: 125.93,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '5623320-ZN',
    price: 138.36,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '5624192-ZN',
    price: 146.49,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '5624256-ZN',
    price: 85.64,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '5624320-ZN',
    price: 120.14,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '5625192-ZN',
    price: 107.54,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '5625288-ZN',
    price: 129.38,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '5625384-ZN',
    price: 179.96,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '5616056-SS',
    price: 329.09,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '5616072-SS',
    price: 355.92,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5616104-SS',
    price: 430.5,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5618072-SS',
    price: 613.08,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5618088-SS',
    price: 652.17,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5618096-SS',
    price: 687.25,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5618120-SS',
    price: 803.51,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
  {
    name: 'Wiper Blades Brandix WL2',
    slug: 'wiper-blades-brandix-wl2',
    sku: '5618160-SS',
    price: 488.09,
    images: [
      '/images/products/product-12-1.jpg',
      '/images/products/product-12-2.jpg',
    ],
    rating: 5,
    reviews: 41,
    availability: 'in-stock',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Fantastic 12-Stroke Engine With A Power of 1991 hp',
    slug: 'fantastic-12-stroke-engine-with-a-power-of-1991-hp',
    sku: '5620088-SS',
    price: 561.54,
    images: [
      '/images/products/product-13-1.jpg',
      '/images/products/product-13-2.jpg',
    ],
    rating: 3,
    reviews: 17,
    availability: 'in-stock',
    attributes: {
      Color: 'Emerald',
    },
  },
  {
    name: 'Set of Four 19 Inch Spiked Tires',
    slug: 'set-of-four-19-inch-spiked-tires',
    sku: '5620120-SS',
    price: 683.71,
    images: [
      '/images/products/product-14-1.jpg',
      '/images/products/product-14-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: '40 Megawatt Low Beam Lamp',
    slug: '40-megawatt-low-beam-lamp',
    sku: '5620136-SS',
    price: 364.08,
    compareAtPrice: 8,
    images: [
      '/images/products/product-15-1.jpg',
      '/images/products/product-15-2.jpg',
    ],
    rating: 4,
    reviews: 31,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shakespeare',
    },
  },
  {
    name: "Brandix Driver's seat",
    slug: 'brandix-drivers-seat',
    sku: '5620176-SS',
    price: 437.04,
    images: [
      '/images/products/product-16-1.jpg',
      '/images/products/product-16-2.jpg',
    ],
    rating: 3,
    reviews: 4,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Blue',
    },
  },
  {
    name: "Air Filter From Ash's Chainsaw",
    slug: 'air-filter-from-ashs-chainsaw',
    sku: '5620224-SS',
    price: 540.38,
    images: [
      '/images/products/product-17-1.jpg',
      '/images/products/product-17-2.jpg',
    ],
    rating: 5,
    reviews: 66,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Side Rearview Mirror',
    slug: 'side-rearview-mirror',
    sku: '5622112-SS',
    price: 539.33,
    compareAtPrice: 60,
    images: [
      '/images/products/product-18-1.jpg',
      '/images/products/product-18-2.jpg',
    ],
    rating: 4,
    reviews: 25,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Violet',
    },
  },
  {
    name: 'Brandix Car Door Lock',
    slug: 'brandix-car-door-lock',
    sku: '5622144-SS',
    price: 588.04,
    compareAtPrice: 31,
    images: [
      '/images/products/product-19-1.jpg',
      '/images/products/product-19-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 24,
    availability: 'in-stock',
    brand: 'turbo-electric',
    attributes: {
      Color: 'Purple',
    },
  },
  {
    name: 'Air Suspension For Brandix Car',
    slug: 'air-suspension-for-brandix-car',
    sku: '5622160-SS',
    price: 618.08,
    compareAtPrice: 174,
    images: [
      '/images/products/product-20-1.jpg',
      '/images/products/product-20-2.jpg',
    ],
    rating: 5,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Cerise',
    },
  },
  {
    name: 'Sunset Brake Kit',
    slug: 'sunset-brake-kit',
    sku: '5622192-SS',
    price: 689.04,
    images: [
      '/images/products/product-21-1.jpg',
      '/images/products/product-21-2.jpg',
    ],
    rating: 4,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Specter Brake Kit',
    slug: 'specter-brake-kit',
    sku: '5622224-SS',
    price: 795.71,
    images: [
      '/images/products/product-22-1.jpg',
      '/images/products/product-22-2.jpg',
    ],
    rating: 5,
    reviews: 3,
    availability: 'in-stock',
    brand: 'specter',
    attributes: {
      Color: 'Green',
    },
  },
  {
    name: 'Brake Kit',
    slug: 'brake-kit',
    sku: '5622272-SS',
    price: 923.52,
    images: [
      '/images/products/product-23-1.jpg',
      '/images/products/product-23-2.jpg',
    ],
    rating: 3,
    reviews: 9,
    availability: 'in-stock',
    brand: 'no-name',
    attributes: {
      Color: 'Shamrock',
    },
  },
  {
    name: 'STP Generator Platinum',
    slug: 'stp-generator-platinum',
    sku: '5623136-SS',
    price: 658.08,
    images: [
      '/images/products/product-24-1.jpg',
      '/images/products/product-24-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Blue',
    },
  },
  {
    name: 'Brandix Spark Plug Kit ASR-400',
    slug: 'brandix-spark-plug-kit-asr-400',
    sku: '5623152-SS',
    price: 743.42,
    images: [
      '/images/products/product-1-1.jpg',
      '/images/products/product-1-2.jpg',
    ],
    badges: ['sale', 'new', 'hot'],
    rating: 4,
    reviews: 3,
    availability: 'in-stock',
    compatibility: [1, 2],
    attributes: {
      Color: 'White',
    },
  },
  {
    name: 'Brandix Brake Kit BDX-750Z370-S',
    slug: 'brandix-brake-kit-bdx-750z370-s',
    sku: '5623176-SS',
    price: 784.58,
    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
  },
  {
    name: 'Left Headlight Of Brandix Z54',
    slug: 'left-headlight-of-brandix-z54',
    sku: '5623224-SS',
    price: 468.0,
    compareAtPrice: 415,
    images: [
      '/images/products/product-3-1.jpg',
      '/images/products/product-3-2.jpg',
    ],
    badges: ['sale'],
    rating: 3,
    reviews: 14,
    availability: 'in-stock',
    attributes: {
      Color: 'Red',
    },
  },
  {
    name: "Glossy Gray 19' Aluminium Wheel AR-19",
    slug: 'glossy-gray-19-aluminium-wheel-ar-19',
    sku: '5623272-SS',
    price: 530.96,
    images: [
      '/images/products/product-4-1.jpg',
      '/images/products/product-4-2.jpg',
    ],
    badges: ['hot'],
    rating: 4,
    reviews: 26,
    availability: 'in-stock',
    compatibility: 'unknown',
    attributes: {
      Color: 'Black',
    },
  },
  {
    name: 'Twin Exhaust Pipe From Brandix Z54',
    slug: 'twin-exhaust-pipe-from-brandix-z54',
    sku: '5623320-SS',
    price: 624.33,
    images: [
      '/images/products/product-5-1.jpg',
      '/images/products/product-5-2.jpg',
    ],
    rating: 4,
    reviews: 9,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Light Gray',
    },
  },
  {
    name: 'Motor Oil Level 5',
    slug: 'motor-oil-level-5',
    sku: '5624192-SS',
    price: 655.04,
    images: [
      '/images/products/product-6-1.jpg',
      '/images/products/product-6-2.jpg',
    ],
    rating: 5,
    reviews: 2,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Gray',
    },
  },
  {
    name: 'Brandix Engine Block Z4',
    slug: 'brandix-engine-block-z4',
    sku: '5624256-SS',
    price: 382.04,
    compareAtPrice: 573,
    images: [
      '/images/products/product-7-1.jpg',
      '/images/products/product-7-2.jpg',
    ],
    rating: 0,
    reviews: 0,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Dark Gray',
    },
  },
  {
    name: 'Brandix Clutch Discs Z175',
    slug: 'brandix-clutch-discs-z175',
    sku: '5624320-SS',
    price: 454.96,
    images: [
      '/images/products/product-8-1.jpg',
      '/images/products/product-8-2.jpg',
    ],
    rating: 3,
    reviews: 7,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Coal',
    },
  },
  {
    name: 'Brandix Manual Five Speed Gearbox',
    slug: 'brandix-manual-five-speed-gearbox',
    sku: '5625192-SS',
    price: 369.54,
    images: [
      '/images/products/product-9-1.jpg',
      '/images/products/product-9-2.jpg',
    ],
    rating: 4,
    reviews: 6,
    availability: 'in-stock',
    brand: 'sunset',
    attributes: {
      Color: 'Orange',
    },
  },
  {
    name: 'Set of Car Floor Mats Brandix Z4',
    slug: 'set-of-car-floor-mats-brandix-z4',
    sku: '5625288-SS',
    price: 510.79,
    compareAtPrice: 94,
    images: [
      '/images/products/product-10-1.jpg',
      '/images/products/product-10-2.jpg',
    ],
    rating: 4,
    reviews: 16,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Yellow',
    },
  },
  {
    name: 'Taillights Brandix Z54',
    slug: 'taillights-brandix-z54',
    sku: '5625384-SS',
    price: 684.33,
    images: [
      '/images/products/product-11-1.jpg',
      '/images/products/product-11-2.jpg',
    ],
    rating: 2,
    reviews: 8,
    availability: 'in-stock',
    brand: 'red-gate',
    attributes: {
      Color: 'Pear Green',
    },
  },
];

export const products: IProduct[] = makeProducts(productsDef);
