import { IProduct } from '~/fake-server/interfaces/newProduct';

export const diameters = [
  {
    Diameter: '1/4',
    undefined: '1/4-20',
  },
  {
    Diameter: '5/16',
    undefined: '5/16-18',
  },
  {
    Diameter: '3/8',
    undefined: '3/8-16',
  },
  {
    Diameter: '1/8',
    undefined: '1/2-13',
  },
  {
    Diameter: '1/2',
  },
  {
    Diameter: '3/4-10',
  },
  {
    Diameter: '1/4-10',
  },
  {
    Diameter: '5/16-9',
  },
  {
    Diameter: '3/8-7',
  },
  {
    Diameter: '1/2-6',
  },
  {
    Diameter: '8-32',
  },
  {
    Diameter: '10-24',
  },
  {
    Diameter: '6-32',
  },
  {
    Diameter: '7/8-9',
  },
  {
    Diameter: '1-8',
  },
];

export const sheet13 = [
  {
    Category: 'Conical ',
    description: '6-8 -- Conical Plastic Anchor',
    Diameter: '6-8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '8-10 -- Conical Plastic Anchor',
    Diameter: '8-10',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '10-12 -- Conical Plastic Anchor',
    Diameter: '10-12',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'Conical ',
    description: '14-16 -- Conical Plastic Anchor',
    Diameter: '14-16',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Plastic',
    Finish: 'n/a',
  },
  {
    Category: 'E-Z ',
    description: 'E-Z Anchor -- Metal',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Metal',
    Finish: 'n/a',
  },
  {
    Category: 'E-Z ',
    description: 'E-Z Anchor -- Nylon',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Hammer Drive ',
    description: '3/16 x 7/8 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '3/16',
    Length: '7/8',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 3/4 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '1/4',
    Length: '3/4',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/2 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-1/2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/4 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-1/4',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 1-1/2 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-1/2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hammer Drive ',
    description: '1/4 x 2 -- Hammer Drive -- Anchor -- Zinc Plated',
    Diameter: '1/4',
    Length: '2',
    Head_type: 'Hammer Drive',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'Zinc',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-XS -- Hollow Wall -- Anchor',
    Diameter: '1/8-XS',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-S -- Hollow Wall -- Anchor',
    Diameter: '1/8-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-L -- Hollow Wall -- Anchor',
    Diameter: '1/8-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/8-XL -- Hollow Wall -- Anchor',
    Diameter: '1/8-XL',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-S -- Hollow Wall -- Anchor',
    Diameter: '3/16-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-L -- Hollow Wall -- Anchor',
    Diameter: '3/16-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '3/16-XL -- Hollow Wall -- Anchor',
    Diameter: '3/16-XL',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-S -- Hollow Wall -- Anchor',
    Diameter: '1/4-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-L -- Hollow Wall -- Anchor',
    Diameter: '1/4-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Hollow Wall',
    description: '1/4-XL -- Hollow Wall -- Anchor',
    Diameter: '1/4-XL',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '10 x 1 -- Hex Washer Head SMS -- 10-12 -- Conical Anchor -- Kit',
    Diameter: '10',
    Length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '10 x 1 -- Hex Washer Head SMS -- 10-12 -- Conical Anchor -- Kit (Without Driver Bit)',
    Diameter: '10',
    Length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '10 x 1 -- Combo Pan SMS -- 10-12 -- Conical Anchor -- Kit',
    Diameter: '10',
    Length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '6 x 3/4 -- Slotted Pan SMS -- 6-8 -- Conical Anchor -- Kit',
    Diameter: '6',
    Length: '3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '8 x 1 -- Slotted Pan SMS -- 8-10 -- Conical Anchor -- Kit',
    Diameter: '8',
    Length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description: '10 x 1 -- Slotted Pan SMS -- 10-12 -- Conical Anchor -- Kit',
    Diameter: '10',
    Length: '1',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '12 x 1-1/4 -- Slotted Pan SMS -- 14-16 -- Conical Anchor -- Kit',
    Diameter: '12',
    Length: '1 1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Kit',
    description:
      '14 x 1-1/2 -- Slotted Pan SMS -- 14-16 -- Conical Anchor -- Kit',
    Diameter: '14',
    Length: '1 1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Nail ',
    description: '3/16 x 1 -- Flat Head -- Nylon Nail -- Anchor',
    Diameter: '3/16',
    Length: '1',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1 -- Flat Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '1',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1-1/2 -- Flat Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '1-1/2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 2 -- Flat Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1 -- Mushroom Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '1',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 1-1/2 -- Mushroom Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '1-1/2',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Nail ',
    description: '1/4 x 2 -- Mushroom Head -- Nylon Nail -- Anchor',
    Diameter: '1/4',
    Length: '2',
    Head_type: 'Mushroom Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Nylon',
    Finish: 'Nylon',
  },
  {
    Category: 'Drop-In',
    description: '1/4-20 -- Drop-In Anchor -- Steel -- Zinc Plated',
    Diameter: '1/4-20',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '3/8-16 -- Drop-In Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8-16',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '1/2-13 -- Drop-In Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2-13',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '5/8-11 -- Drop-In Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8-11',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Drop-In',
    description: '3/4-10 -- Drop-In Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4-10',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Machine Screw',
    description: '6-32 -- Machine Screw Anchor',
    Diameter: '6-32',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '8-32 -- Machine Screw Anchor',
    Diameter: '8-32',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '10-24 -- Machine Screw Anchor',
    Diameter: '10-24',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '1/4-20 -- Machine Screw Anchor',
    Diameter: '1/4-20',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '5/16-18 -- Machine Screw Anchor',
    Diameter: '5/16-18',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '3/8-16 -- Machine Screw Anchor',
    Diameter: '3/8-16',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '1/2-13 -- Machine Screw Anchor',
    Diameter: '1/2-13',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '5/8-11 -- Machine Screw Anchor',
    Diameter: '5/8-11',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Machine Screw',
    description: '3/4-10 -- Machine Screw Anchor',
    Diameter: '3/4-10',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#6 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '#6',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#8 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '#8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '#10 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '#10',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.25 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.25',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.3125 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.3125',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.375 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.375',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.5 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.5',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.625 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.625',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '0.75 -- Machine Screw Anchor -- Setting Tool',
    Diameter: '0.75',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '1/4 -- Drop-In Anchor -- Setting Tools',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '3/8 -- Drop-In Anchor -- Setting Tools',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '1/2 -- Drop-In Anchor -- Setting Tools',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '5/8 -- Drop-In Anchor -- Setting Tools',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Setting Tools',
    description: '3/4 -- Drop-In Anchor -- Setting Tools',
    Diameter: 'n/a',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4-S -- Lag Screw --  -- Shield',
    Diameter: '1/4-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16-S -- Lag Screw -- Shield',
    Diameter: '5/16-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8-S -- Lag Screw -- Shield',
    Diameter: '3/8-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2-S -- Lag Screw -- Shield',
    Diameter: '1/2-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8-S -- Lag Screw -- Shield',
    Diameter: '5/8-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4-S -- Lag Screw -- Shield',
    Diameter: '3/4-S',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4-L -- Lag Screw -- Shield',
    Diameter: '1/4-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16-L -- Lag Screw -- Shield',
    Diameter: '5/16-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8-L -- Lag Screw -- Shield',
    Diameter: '3/8-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2-L -- Lag Screw -- Shield',
    Diameter: '1/2-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8-L -- Lag Screw -- Shield',
    Diameter: '5/8-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4-L -- Lag Screw -- Shield',
    Diameter: '3/4-L',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4 -- Single Expansion -- Shield',
    Diameter: '1/4',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16 -- Single Expansion -- Shield',
    Diameter: '5/16',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8 -- Single Expansion -- Shield',
    Diameter: '3/8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2 -- Single Expansion -- Shield',
    Diameter: '1/2',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8 -- Single Expansion -- Shield',
    Diameter: '5/8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4 -- Single Expansion -- Shield',
    Diameter: '3/4',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/4 -- Double Expansion -- Shield',
    Diameter: '1/4',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/16 -- Double Expansion -- Shield',
    Diameter: '5/16',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/8 -- Double Expansion -- Shield',
    Diameter: '3/8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '1/2 -- Double Expansion -- Shield',
    Diameter: '1/2',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '5/8 -- Double Expansion -- Shield',
    Diameter: '5/8',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Shields',
    description: '3/4 -- Double Expansion -- Shield',
    Diameter: '3/4',
    Length: 'n/a',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'n/a',
    Finish: 'n/a',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 X 1-3/8 -- Sleeve Anchor -- Acorn Nut -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-3/8',
    Head_type: 'Acorn Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 X 2-1/4 -- Sleeve Anchor -- Acorn Nut -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '2-1/4',
    Head_type: 'Acorn Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/16 X 1-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/16',
    Length: '1-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/16 X 2-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/16',
    Length: '2-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 X 1-7/8 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '1-7/8',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '3/8 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '3/8 X 4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/2 X 2-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '2-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '1/2 X 6 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '6',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/8 X 2-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '2-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '5/8 X 3 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '3',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '5/8 X 4-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '4-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description: '5/8 X 6 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '6',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 2-1/2 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '2-1/2',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 4-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '4-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/4 X 6-1/4 -- Sleeve Anchor -- Hex Nut -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '6-1/4',
    Head_type: 'Hex Nut',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 2 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '2',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 3 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '3',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 4 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '4',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 3 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '3',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 4 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '4',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 5 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '5',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 6 -- Sleeve Anchor -- Flat Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '6',
    Head_type: 'Flat Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 1-1/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-1/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 2 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '2',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '1/4 x 4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 2-1/2 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '2-1/2',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 3-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '3-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 4-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '4-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 5-3/4 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '5-3/4',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Sleeve',
    description:
      '3/8 x 6 -- Sleeve Anchor -- Round Head -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '6',
    Head_type: 'Round Head',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 X 1-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '1-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 2-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 3-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/4',
    Length: '3-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '3',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 5 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/8',
    Length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 2-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 3-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 4-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 5-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1/2',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 3-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '3-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 4-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '4-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 5 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 8-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '5/8',
    Length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-1/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-3/4 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '4-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4-5-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 7 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 8-1/2 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 10 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '3/4',
    Length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '7/8',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 8 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '7/8',
    Length: '8',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 10 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '7/8',
    Length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 6 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 9 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1',
    Length: '9',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1 x 12 -- Wedge Anchor -- Steel -- Zinc Plated',
    Diameter: '1',
    Length: '12',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: 'n/a',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Category: 'Wedge',
    description: '1/4 X 1-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/4',
    Length: '1-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 2-1/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/4',
    Length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/4 x 3-1/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/4',
    Length: '3-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-1/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/8',
    Length: '2-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 2-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/8',
    Length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/8',
    Length: '3',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 3-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/8',
    Length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/8 x 5 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/8',
    Length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 2-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/2',
    Length: '2-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 3-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/2',
    Length: '3-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 4-1/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/2',
    Length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 5-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/2',
    Length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1/2 x 7 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1/2',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 3-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '3-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 4-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '4-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 5 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '5',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 6 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 7 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '5/8 x 8-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '5/8',
    Length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-1/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '4-1/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 4-3/4 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '4-3/4',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4-5-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '5-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 7 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '7',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 8-1/2 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '8-1/2',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '3/4 x 10 -- Wedge Anchor -- Stainless Steel',
    Diameter: '3/4',
    Length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 6 -- Wedge Anchor -- Stainless Steel',
    Diameter: '7/8',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 8 -- Wedge Anchor -- Stainless Steel',
    Diameter: '7/8',
    Length: '8',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '7/8 x 10 -- Wedge Anchor -- Stainless Steel',
    Diameter: '7/8',
    Length: '10',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 6 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1',
    Length: '6',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 9 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1',
    Length: '9',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
  {
    Category: 'Wedge',
    description: '1 x 12 -- Wedge Anchor -- Stainless Steel',
    Diameter: '1',
    Length: '12',
    Head_type: 'n/a',
    Drive: 'n/a',
    Grade: '303SS',
    Material: 'Stainless Steel',
    Finish: 'n/a',
  },
];

export const Sheet12 = [
  {
    Head_type: 'Acorn Nut',
    Drive: 'Combo',
    Grade: '2',
    Material: 'Metal',
    Finish: 'Black Oxide',
  },
  {
    Head_type: 'Bugle',
    Drive: 'Hex',
    Grade: '5',
    Material: 'Nylon',
    Finish: 'Black Phosphate',
  },
  {
    Head_type: 'Flat',
    Drive: 'Phillips',
    Grade: '8',
    Material: 'Plastic',
    Finish: 'Black Phosphate & Oil',
  },
  {
    Head_type: 'Flat Head',
    Drive: 'Slotted',
    Grade: '18-8',
    Material: 'Stainless Steel',
    Finish: 'Blue',
  },
  {
    Head_type: 'Full Thread',
    Drive: 'Slotted Hex',
    Grade: '18-8SS',
    Material: 'Steel',
    Finish: 'Brown',
  },
  {
    Head_type: 'Hammer Drive',
    Grade: '303SS',
    Finish: 'Dacrotized',
  },
  {
    Head_type: 'Hex',
    Grade: '5',
    Finish: 'Hot Dip Galvanized',
  },
  {
    Head_type: 'Hex Cap',
    Grade: '8',
    Finish: 'Ivory',
  },
  {
    Head_type: 'Hex Nut',
    Grade: 'Alloy',
    Finish: 'Nickel',
  },
  {
    Head_type: 'Hex Washer',
    Grade: 'C',
    Finish: 'Nylon',
  },
  {
    Head_type: 'Indented Hex Flange',
    Grade: 'G',
    Finish: 'Plain',
  },
  {
    Head_type: 'Mushroom',
    Grade: 'Hardened',
    Finish: 'White',
  },
  {
    Head_type: 'Mushroom Head',
    Finish: 'Zinc',
  },
  {
    Head_type: 'Oval',
    Finish: 'Zinc & Dichromate',
  },
  {
    Head_type: 'Pan',
    Finish: 'Zinc Yellow',
  },
  {
    Head_type: 'Round',
  },
  {
    Head_type: 'Round Head',
  },
  {
    Head_type: 'Slotted',
  },
];

export const Attributes = [
  {
    Diameter: '#4',
    Length: 'xs',
    'Thread Size': 'Inch',
    undefined: 'Fine',
    'Thread Type (metric)': 'Coarse',
    'Screw Size': '6-8',
  },
  {
    Diameter: '#6',
    Length: 's',
    'Thread Size': 'Coarse',
    undefined: 'Partial',
    'Thread Type (metric)': 'Full',
    'Screw Size': '8-10',
  },
  {
    Diameter: '#8',
    Length: 'l',
    'Thread Size': '#2-56',
    undefined: 'DIN 960',
    'Thread Type (metric)': 'DIN 933',
    'Screw Size': '10-12',
  },
  {
    Diameter: '#10',
    Length: 'xl',
    'Thread Size': '#3-48',
    undefined: 'M4-0.7',
    'Screw Size': '14-16',
  },
  {
    Diameter: '1/8',
    Length: 'short',
    'Thread Size': '#4-40',
    undefined: 'M5-0.8',
  },
  {
    Diameter: '3/16',
    Length: 'long',
    'Thread Size': '#6-32',
    undefined: 'M6-1.00',
  },
  {
    Diameter: '1/4',
    'Thread Size': '#8-32',
    undefined: 'M7-1.00',
  },
  {
    Diameter: '5/16',
    'Thread Size': '#10-24',
    undefined: 'M8-1.00',
  },
  {
    Diameter: '3/8',
    'Thread Size': '1/4"-20',
    undefined: 'M10-1.00',
  },
  {
    Diameter: '7/16',
    'Thread Size': '5/16"-18',
    undefined: 'M10-1.25',
  },
  {
    Diameter: '1/2',
    'Thread Size': '3/8"-16',
    undefined: 'M12-1.25',
  },
  {
    Diameter: '9/16',
    'Thread Size': '7/16"-14',
    undefined: 'M12-1.50',
  },
  {
    Diameter: '5/8',
    'Thread Size': '1/2"-13',
    undefined: 'M14-1.50',
  },
  {
    Diameter: '3/4',
    'Thread Size': '9/16"-12',
    undefined: 'M16-1.50',
  },
  {
    Diameter: '7/8',
    'Thread Size': '5/8"-11',
    undefined: 'M18-1.50',
  },
  {
    Diameter: '1',
    'Thread Size': '3/4"-10',
    undefined: 'M20-1.50',
  },
  {
    Diameter: '1 1/8',
    'Thread Size': '7/8"-9',
    undefined: 'M22-1.50',
  },
  {
    Diameter: '1 1/4',
    'Thread Size': '1"-8',
    undefined: 'M24-2.00',
  },
  {
    Diameter: '1 3/8',
    'Thread Size': '1-1/8"-7',
    undefined: 'M27-3.00',
  },
  {
    Diameter: '1 1/2',
    'Thread Size': '1-1/4"-7',
    undefined: 'M30-3.50',
  },
  {
    Diameter: '1 3/4',
    'Thread Size': '1-3/8"-6',
    undefined: 'M33-3.50',
  },
  {
    Diameter: '2',
    'Thread Size': '1-1/2"-6',
    undefined: 'M36-4.00',
  },
  {
    Diameter: '2 1/4',
    'Thread Size': '1-3/4"-5',
    undefined: 'M39-4.00',
  },
  {
    Diameter: '2 1/2',
    'Thread Size': '2"-4-1/2',
    undefined: 'M42-4.50',
  },
  {
    Diameter: '2 3/4',
    'Thread Size': '2-1/2"-4-12',
    undefined: 'M45-4.50',
  },
  {
    Diameter: '3',
    'Thread Size': '2-3/4"-4',
    undefined: 'M48-5.00',
  },
  {
    'Thread Size': '3"-4',
    undefined: '3"-12',
  },
];

export const attributes_2 = [
  {
    Diameter: '#2',
    Length: 'xs',
    'Threads (Coarse)': '#2-56',
    'Threads (Fine)': '#10-32',
    'Thread Type (metric)': 'Coarse',
    'Thread Size': 'Inch',
    undefined: 'Fine',
    'Screw Size': '6-8',
  },
  {
    Diameter: '#3',
    Length: 's',
    'Threads (Coarse)': '#3-48',
    'Threads (Fine)': '1/4"-28',
    'Thread Type (metric)': 'Full',
    'Thread Size': 'Coarse',
    undefined: 'Partial',
    'Screw Size': '8-10',
    Material: 'Steel',
    Finish: 'Zinc',
  },
  {
    Diameter: '#4',
    Length: 'l',
    'Threads (Coarse)': '#4-40',
    'Threads (Fine)': '5/16"-24',
    'Thread Size': '#2-56',
    undefined: 'DIN 960',
    'Thread Type (metric)': 'DIN 933',
    'Screw Size': '10-12',
    Material: 'Stainless Steel',
    Finish: 'Zinc & Dichromate',
  },
  {
    Diameter: '#6',
    Length: 'xl',
    'Threads (Coarse)': '#6-32',
    'Threads (Fine)': '3/8"-24',
    'Thread Size': '#3-48',
    undefined: 'FILTERS',
    'Screw Size': '14-16',
    Finish: 'n/a',
  },
  {
    Diameter: '#8',
    Length: 'short',
    'Threads (Coarse)': '#8-32',
    'Threads (Fine)': '7/16"-20',
    'Thread Size': '#4-40',
    undefined: 'THREAD SIZE',
  },
  {
    Diameter: '#10',
    Length: 'long',
    'Threads (Coarse)': '#10-24',
    'Threads (Fine)': '1/2"-20',
    'Thread Size': '#6-32',
    undefined: 'Metric',
  },
  {
    Diameter: '1/8',
    'Threads (Coarse)': '1/4"-20',
    'Threads (Fine)': '9/16"-18',
    'Thread Size': '#8-32',
    undefined: 'Inch',
  },
  {
    Diameter: '3/16',
    'Threads (Coarse)': '5/16"-18',
    'Threads (Fine)': '5/8"-18',
    'Thread Size': '#10-24',
    undefined: 'M8-1.00',
  },
  {
    Diameter: '1/4',
    'Threads (Coarse)': '3/8"-16',
    'Threads (Fine)': '3/4"-16',
    'Thread Size': '1/4"-20',
    undefined: 'Coarse',
  },
  {
    Diameter: '5/16',
    'Threads (Coarse)': '7/16"-14',
    'Threads (Fine)': '7/8"-14',
    'Thread Size': '5/16"-18',
    undefined: 'Fine',
  },
  {
    Diameter: '3/8',
    'Threads (Coarse)': '1/2"-13',
    'Threads (Fine)': '1"-14',
    'Thread Size': '3/8"-16',
    undefined: 'M12-1.25',
  },
  {
    Diameter: '7/16',
    'Threads (Coarse)': '9/16"-12',
    'Threads (Fine)': '1-1/8"-12',
    'Thread Size': '7/16"-14',
    undefined: 'Full',
  },
  {
    Diameter: '1/2',
    'Threads (Coarse)': '5/8"-11',
    'Threads (Fine)': '1-1/4"-12',
    'Thread Size': '1/2"-13',
    undefined: 'Partial',
  },
  {
    Diameter: '9/16',
    'Threads (Coarse)': '3/4"-10',
    'Threads (Fine)': '1-3/8"-12',
    'Thread Size': '9/16"-12',
    undefined: 'M16-1.50',
  },
  {
    Diameter: '5/8',
    'Threads (Coarse)': '7/8"-9',
    'Threads (Fine)': '1-1/2"-12',
    'Thread Size': '5/8"-11',
    undefined: 'M18-1.50',
  },
  {
    Diameter: '3/4',
    'Threads (Coarse)': '1"-8',
    'Threads (Fine)': '1-3/4"-12',
    'Thread Size': '3/4"-10',
    undefined: 'M20-1.50',
  },
  {
    Diameter: '7/8',
    'Threads (Coarse)': '1-1/8"-7',
    'Threads (Fine)': '2"-12',
    'Thread Size': '7/8"-9',
    undefined: 'M22-1.50',
  },
  {
    Diameter: '1',
    'Threads (Coarse)': '1-1/4"-7',
    'Threads (Fine)': '2-1/2"-12',
    'Thread Size': '1"-8',
    undefined: 'M24-2.00',
  },
  {
    Diameter: '1 1/8',
    'Threads (Coarse)': '1-3/8"-6',
    'Threads (Fine)': '2-3/4"-12',
    'Thread Size': '1-1/8"-7',
    undefined: 'M27-3.00',
  },
  {
    Diameter: '1 1/4',
    'Threads (Coarse)': '1-1/2"-6',
    'Threads (Fine)': '3"-12',
    'Thread Size': '1-1/4"-7',
    undefined: 'M30-3.50',
  },
  {
    Diameter: '1 3/8',
    'Threads (Coarse)': '1-3/4"-5',
    'Threads (Fine)': 'M8-1.00',
    'Thread Size': '1-3/8"-6',
    undefined: 'M33-3.50',
  },
  {
    Diameter: '1 1/2',
    'Threads (Coarse)': '2"-4-1/2',
    'Threads (Fine)': 'M10-1.00',
    'Thread Size': '1-1/2"-6',
    undefined: 'M36-4.00',
  },
  {
    Diameter: '1 3/4',
    'Threads (Coarse)': '2-1/2"-4-12',
    'Threads (Fine)': 'M10-1.25',
    'Thread Size': '1-3/4"-5',
    undefined: 'M39-4.00',
  },
  {
    Diameter: '2',
    'Threads (Coarse)': '2-3/4"-4',
    'Threads (Fine)': 'M12-1.25',
    'Thread Size': '2"-4-1/2',
    undefined: 'M42-4.50',
  },
  {
    Diameter: '2 1/4',
    'Threads (Coarse)': '3"-4',
    'Threads (Fine)': 'M12-1.50',
    'Thread Size': '2-1/2"-4-12',
    undefined: 'M45-4.50',
  },
  {
    Diameter: '2 1/2',
    'Threads (Coarse)': 'M3-0.5',
    'Threads (Fine)': 'M14-1.50',
    'Thread Size': '2-3/4"-4',
    undefined: 'M48-5.00',
  },
  {
    Diameter: '2 3/4',
    'Threads (Coarse)': 'M4-0.7',
    'Threads (Fine)': 'M16-1.50',
    'Thread Size': '3"-4',
    undefined: '3"-12',
  },
  {
    Diameter: '3',
    'Threads (Coarse)': 'M5-0.8',
    'Threads (Fine)': 'M18-1.50',
  },
  {
    'Threads (Coarse)': 'M6-1.00',
    'Threads (Fine)': 'M20-1.50',
  },
  {
    'Threads (Coarse)': 'M7-1.00',
    'Threads (Fine)': 'M22-1.50',
  },
  {
    'Threads (Coarse)': 'M8-1.25',
    'Threads (Fine)': 'M24-2.00',
  },
  {
    'Threads (Coarse)': 'M10-1.50',
  },
  {
    'Threads (Coarse)': 'M12-1.75',
  },
  {
    'Threads (Coarse)': 'M14-2.00',
  },
  {
    'Threads (Coarse)': 'M16-2.00',
  },
  {
    'Threads (Coarse)': 'M18-2.50',
  },
  {
    'Threads (Coarse)': 'M20-2.50',
  },
  {
    'Threads (Coarse)': 'M22-2.50',
  },
  {
    'Threads (Coarse)': 'M24-3.00',
  },
  {
    'Threads (Coarse)': 'M27-3.00',
  },
  {
    'Threads (Coarse)': 'M30-3.50',
  },
  {
    'Threads (Coarse)': 'M33-3.50',
  },
  {
    'Threads (Coarse)': 'M36-4.00',
  },
  {
    'Threads (Coarse)': 'M39-4.00',
  },
  {
    'Threads (Coarse)': 'M42-4.50',
  },
  {
    'Threads (Coarse)': 'M45-4.50',
  },
  {
    'Threads (Coarse)': 'M48-5.00',
  },
];

export const attribute_3 = [
  {
    Diameter: '#2',
    Length: 'xs',
    'Thread Size': 'Inch',
    undefined: 'Metric',
    'Thread Length': 'Inch',
    'Thread Coverage': 'Full',
    'Screw Size': '6-8',
  },
  {
    Diameter: '#3',
    Length: 's',
    'Thread Size': '#2-56',
    undefined: '5',
    'Thread Length': '1/8',
    'Thread Coverage': 'Partial',
    'Screw Size': '8-10',
  },
  {
    Diameter: '#4',
    Length: 'l',
    'Thread Size': '#3-48',
    undefined: '6',
    'Thread Length': '3/16',
    'Screw Size': '10-12',
  },
  {
    Diameter: '#6',
    Length: 'xl',
    'Thread Size': '#4-40',
    undefined: '8',
    'Thread Length': '1/4',
    'Screw Size': '14-16',
  },
  {
    Diameter: '#8',
    Length: 'short',
    'Thread Size': '#6-32',
    undefined: '10',
    'Thread Length': '5/16',
  },
  {
    Diameter: '#10',
    Length: 'long',
    'Thread Size': '#8-32',
    undefined: '12',
    'Thread Length': '3/8',
  },
  {
    Diameter: '1/8',
    'Thread Size': '#10-24',
    undefined: '14',
    'Thread Length': '7/16',
  },
  {
    Diameter: '3/16',
    'Thread Size': '#10-32',
    undefined: '16',
    'Thread Length': '1/2',
  },
  {
    Diameter: '1/4',
    'Thread Size': '1/2"-13',
    undefined: '18',
    'Thread Length': '5/8',
  },
  {
    Diameter: '5/16',
    'Thread Size': '1/2"-20',
    undefined: '20 ',
    'Thread Length': '3/4',
  },
  {
    Diameter: '3/8',
    'Thread Size': '1/4"-20',
    undefined: '25 ',
    'Thread Length': '7/8',
  },
  {
    Diameter: '7/16',
    'Thread Size': '1/4"-28',
    undefined: '30 ',
    'Thread Length': '1',
  },
  {
    Diameter: '1/2',
    'Thread Size': '3/4"-10',
    undefined: '35 ',
    'Thread Length': '1 1/8',
  },
  {
    Diameter: '9/16',
    'Thread Size': '3/4"-16',
    undefined: '40 ',
    'Thread Length': '1 1/4',
  },
  {
    Diameter: '5/8',
    'Thread Size': '3/8"-16',
    undefined: '45 ',
    'Thread Length': '1 3/8',
  },
  {
    Diameter: '3/4',
    'Thread Size': '3/8"-24',
    undefined: '50 ',
    'Thread Length': '1 1/2',
  },
  {
    Diameter: '7/8',
    'Thread Size': '5/16"-18',
    undefined: '55 ',
    'Thread Length': '1 3/4',
  },
  {
    Diameter: '1',
    'Thread Size': '5/16"-24',
    undefined: '60',
    'Thread Length': '2',
  },
  {
    Diameter: '1 1/8',
    'Thread Size': '5/8"-11',
    undefined: '65',
    'Thread Length': '2 1/4',
  },
  {
    Diameter: '1 1/4',
    'Thread Size': '5/8"-18',
    undefined: '70',
    'Thread Length': '2 1/2',
  },
  {
    Diameter: '1 3/8',
    'Thread Size': '7/16"-14',
    undefined: '75',
    'Thread Length': '2 3/4',
  },
  {
    Diameter: '1 1/2',
    'Thread Size': '7/16"-20',
    undefined: '80',
    'Thread Length': '3',
  },
  {
    Diameter: '1 3/4',
    'Thread Size': '7/8"-14',
    undefined: '90',
    'Thread Length': '3 1/4',
  },
  {
    Diameter: '2',
    'Thread Size': '7/8"-9',
    undefined: '100',
    'Thread Length': '3 1/2',
  },
  {
    Diameter: '2 1/4',
    'Thread Size': '9/16"-12',
    undefined: '110',
    'Thread Length': '3 3/4',
  },
  {
    Diameter: '2 1/2',
    'Thread Size': '9/16"-18',
    undefined: '120',
    'Thread Length': '4',
  },
  {
    Diameter: '2 3/4',
    'Thread Size': '1-1/2"-12',
    undefined: '130',
    'Thread Length': '4 1/4',
  },
  {
    Diameter: '3',
    'Thread Size': '1-1/2"-6',
    undefined: '140 ',
    'Thread Length': '4 1/2',
  },
  {
    'Thread Size': '1-1/4"-12',
    undefined: '150',
    'Thread Length': '4 3/4',
  },
  {
    'Thread Size': '1-1/4"-7',
    undefined: '160 ',
    'Thread Length': '5',
  },
  {
    'Thread Size': '1-1/8"-12',
    undefined: '170',
    'Thread Length': '5 1/2',
  },
  {
    'Thread Size': '1-1/8"-7',
    undefined: '180',
    'Thread Length': '6',
  },
  {
    'Thread Size': '1-3/4"-12',
    undefined: '200',
    'Thread Length': '6 1/2',
  },
  {
    'Thread Size': '1-3/4"-5',
    undefined: 'M8-1.25',
    'Thread Length': '7',
  },
  {
    'Thread Size': '1-3/8"-12',
    'Thread Length': '7 1/2',
  },
  {
    'Thread Size': '1-3/8"-6',
    'Thread Length': '8',
  },
  {
    'Thread Size': '1"-14',
    'Thread Length': '8 1/2',
  },
  {
    'Thread Size': '1"-8',
    'Thread Length': '9',
  },
  {
    'Thread Size': '2-1/2"-12',
    'Thread Length': '9 1/2',
  },
  {
    'Thread Size': '2-1/2"-4-12',
    'Thread Length': '10',
  },
  {
    'Thread Size': '2-3/4"-12',
    'Thread Length': '11',
  },
  {
    'Thread Size': '2-3/4"-4',
    'Thread Length': '12',
  },
  {
    'Thread Size': '2"-12',
    'Thread Length': '13',
  },
  {
    'Thread Size': '2"-4-1/2',
    'Thread Length': '14',
  },
  {
    'Thread Size': '3"-12',
    'Thread Length': '15',
  },
  {
    'Thread Size': '3"-4',
    'Thread Length': '16',
  },
];

export const Sheet_16 = [
  {
    'Thread Size': 'Inch',
    undefined: '$???',
    'Thread Length': 'Inch',
  },
  {
    'Thread Size': '#2-56',
    undefined: '$???',
    'Thread Length': '1/8',
  },
  {
    'Thread Size': '#3-48',
    undefined: '$???',
    'Thread Length': '3/16',
  },
  {
    'Thread Size': '#4-40',
    undefined: '$???',
    'Thread Length': '1/4',
  },
  {
    'Thread Size': '#6-32',
    undefined: '10',
    'Thread Length': '5/16',
  },
  {
    'Thread Size': '#8-32',
    undefined: '12',
    'Thread Length': '3/8',
  },
  {
    'Thread Size': '#10-24',
    undefined: '14',
    'Thread Length': '7/16',
  },
  {
    'Thread Size': '#10-32',
    undefined: '16',
    'Thread Length': '1/2',
  },
  {
    'Thread Size': '1/2"-13',
    undefined: '18',
    'Thread Length': '5/8',
  },
  {
    'Thread Size': '1/2"-20',
    undefined: '20 ',
    'Thread Length': '3/4',
  },
  {
    'Thread Size': '1/4"-20',
    undefined: '25 ',
    'Thread Length': '7/8',
  },
];


