export const pins: any[] = [
  {
    sku: '5902016-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/16 x 1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/16',
    length: '1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '6.24',
    net_per_box: '1.87',
  },
  {
    sku: '5902024-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/16 x 3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/16',
    length: '3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '4.08',
    net_per_box: '1.22',
  },
  {
    sku: '5902032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/16 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/16',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '4.72',
    net_per_box: '1.42',
  },
  {
    sku: '5902064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/16 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/16',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '10.72',
    net_per_box: '3.22',
  },
  {
    sku: '5903016-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '4.20',
    net_per_box: '1.26',
  },
  {
    sku: '5903024-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '5.00',
    net_per_box: '1.50',
  },
  {
    sku: '5903032-ZN-50',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '4.44',
    net_per_box: '1.33',
  },
  {
    sku: '5903032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '5.60',
    net_per_box: '1.68',
  },
  {
    sku: '5903040-ZN-50',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '5.04',
    net_per_box: '1.51',
  },
  {
    sku: '5903040-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '6.60',
    net_per_box: '1.98',
  },
  {
    sku: '5903048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '7.52',
    net_per_box: '2.26',
  },
  {
    sku: '5903056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '8.36',
    net_per_box: '2.51',
  },
  {
    sku: '5903064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '9.04',
    net_per_box: '2.71',
  },
  {
    sku: '5903072-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 2-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '2-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '12.72',
    net_per_box: '3.82',
  },
  {
    sku: '5903080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '13.08',
    net_per_box: '3.92',
  },
  {
    sku: '5903096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/32 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/32',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '22.48',
    net_per_box: '6.74',
  },
  {
    sku: '5904016-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '4.96',
    net_per_box: '1.49',
  },
  {
    sku: '5904024-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '6.04',
    net_per_box: '1.81',
  },
  {
    sku: '5904032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '7.32',
    net_per_box: '2.20',
  },
  {
    sku: '5904040-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '12.20',
    net_per_box: '3.66',
  },
  {
    sku: '5904048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '9.52',
    net_per_box: '2.86',
  },
  {
    sku: '5904056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '10.72',
    net_per_box: '3.22',
  },
  {
    sku: '5904064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '11.92',
    net_per_box: '3.58',
  },
  {
    sku: '5904072-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 2-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '2-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '15.04',
    net_per_box: '4.51',
  },
  {
    sku: '5904080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '15.36',
    net_per_box: '4.61',
  },
  {
    sku: '5904096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/8 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/8',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '17.68',
    net_per_box: '5.30',
  },
  {
    sku: '5905024-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '9.04',
    net_per_box: '2.71',
  },
  {
    sku: '5905032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '10.76',
    net_per_box: '3.23',
  },
  {
    sku: '5905040-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '12.64',
    net_per_box: '3.79',
  },
  {
    sku: '5905048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '14.32',
    net_per_box: '4.30',
  },
  {
    sku: '5905056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '15.92',
    net_per_box: '4.78',
  },
  {
    sku: '5905064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '17.48',
    net_per_box: '5.24',
  },
  {
    sku: '5905072-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 2-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '2-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '20.00',
    net_per_box: '6.00',
  },
  {
    sku: '5905080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '20.84',
    net_per_box: '6.25',
  },
  {
    sku: '5905096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/32 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/32',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '26.76',
    net_per_box: '8.03',
  },
  {
    sku: '5906024-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '12.28',
    net_per_box: '3.68',
  },
  {
    sku: '5906032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '14.56',
    net_per_box: '4.37',
  },
  {
    sku: '5906040-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '16.84',
    net_per_box: '5.05',
  },
  {
    sku: '5906048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '19.04',
    net_per_box: '5.71',
  },
  {
    sku: '5906056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '21.16',
    net_per_box: '6.35',
  },
  {
    sku: '5906064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '23.84',
    net_per_box: '7.15',
  },
  {
    sku: '5906072-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 2-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '2-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '25.68',
    net_per_box: '7.70',
  },
  {
    sku: '5906080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '29.40',
    net_per_box: '8.82',
  },
  {
    sku: '5906096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '33.48',
    net_per_box: '10.04',
  },
  {
    sku: '5906112-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 X 3-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '3-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '40.16',
    net_per_box: '12.05',
  },
  {
    sku: '5906128-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/16 x 4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/16',
    length: '4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '45.24',
    net_per_box: '13.57',
  },
  {
    sku: '5907032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '7/32 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '7/32',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '21.79',
    net_per_box: '6.54',
  },
  {
    sku: '5907048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '7/32 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '7/32',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '28.91',
    net_per_box: '8.67',
  },
  {
    sku: '5907064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '7/32 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '7/32',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '35.93',
    net_per_box: '10.78',
  },
  {
    sku: '5907080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '7/32 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '7/32',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '42.88',
    net_per_box: '12.86',
  },
  {
    sku: '5908032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '22.20',
    net_per_box: '6.66',
  },
  {
    sku: '5908040-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 1-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '25.52',
    net_per_box: '7.66',
  },
  {
    sku: '5908048-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 1-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '29.32',
    net_per_box: '8.80',
  },
  {
    sku: '5908056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '32.76',
    net_per_box: '9.83',
  },
  {
    sku: '5908064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '36.32',
    net_per_box: '10.90',
  },
  {
    sku: '5908072-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 2-1/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2-1/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '40.12',
    net_per_box: '12.04',
  },
  {
    sku: '5908080-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 2-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '2-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '43.28',
    net_per_box: '12.98',
  },
  {
    sku: '5908096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '50.56',
    net_per_box: '15.17',
  },
  {
    sku: '5908112-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 X 3-1/2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '3-1/2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '58.48',
    net_per_box: '17.54',
  },
  {
    sku: '5908128-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/4 x 4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/4',
    length: '4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '65.60',
    net_per_box: '19.68',
  },
  {
    sku: '5910032-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/16 x 1 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '1',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '100',
    list_price: '34.06',
    net_per_box: '10.22',
  },
  {
    sku: '5910064-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/16 x 2 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '2',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '28.08',
    net_per_box: '8.42',
  },
  {
    sku: '5910096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/16 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '38.03',
    net_per_box: '11.41',
  },
  {
    sku: '5910128-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/16 x 4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/16',
    length: '4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '47.98',
    net_per_box: '14.39',
  },
  {
    sku: '5912056-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/8 x 1-3/4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '1-3/4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '40.29',
    net_per_box: '12.09',
  },
  {
    sku: '5912096-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/8 x 3 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '3',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '50',
    list_price: '54.97',
    net_per_box: '16.49',
  },
  {
    sku: '5912192-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/8 x 6 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '6',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '25',
    list_price: '53.56',
    net_per_box: '16.07',
  },
  {
    sku: '5912256-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '3/8 x 8 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '3/8',
    length: '8',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '25',
    list_price: '58.99',
    net_per_box: '17.70',
  },
  {
    sku: '5916128-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/2 x 4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '20',
    list_price: '61.71',
    net_per_box: '18.51',
  },
  {
    sku: '5916160-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/2 x 5 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '5',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '20',
    list_price: '81.17',
    net_per_box: '24.35',
  },
  {
    sku: '5916192-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '1/2 x 6 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '1/2',
    length: '6',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '20',
    list_price: '95.76',
    net_per_box: '28.73',
  },
  {
    sku: '5920128-ZN',
    name: 'Test',
    slug: 'Test',

    Type: 'Pins',
    superCategory: 'fasteners',

    images: [
      '/images/products/product-2-1.jpg',
      '/images/products/product-2-2.jpg',
    ],
    rating: 5,
    reviews: 22,
    compareAtPrice: 415,
    availability: 'in-stock',
    compatibility: [1],
    attributes: {
      Color: 'Silver',
    },
    Category: 'Cotter Pins',
    description: '5/8 x 4 -- Cotter Pin -- Steel -- Zinc Plated',
    diameter: '5/8',
    length: '4',
    head_type: 'n/a',
    drive: 'n/a',
    grade: 'n/a',
    material: 'Steel',
    finish: 'Zinc',
    qty_per_box: '20',
    list_price: '132.08',
    net_per_box: '39.62',
  },
];
